# Generated by Django 4.1.7 on 2023-03-15 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='new_desc',
            new_name='news_desc',
        ),
    ]
