# Generated by Django 4.1.7 on 2023-03-27 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_new_desc_news_news_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_desc',
        ),
    ]
