# Generated by Django 4.1.7 on 2023-03-27 05:47

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_news_news_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_desc',
            field=tinymce.models.HTMLField(default=None),
        ),
    ]
