# Generated by Django 4.1.7 on 2023-04-06 11:05

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_news_news_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='news_desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
