# Generated by Django 4.1.7 on 2023-03-27 05:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_desc',
            field=tinymce.models.HTMLField(),
        ),
    ]
